# --- !Ups

CREATE TABLE "user" (ID VARCHAR(100) NOT NULL, PROVIDER VARCHAR(100), FIRST_NAME VARCHAR(200), LAST_NAME VARCHAR(200), EMAIL VARCHAR(100), "password" VARCHAR(100));
CREATE TABLE TOKEN (UUID VARCHAR(100) NOT NULL PRIMARY KEY, EMAIL VARCHAR(100), CREATION_TIME TIMESTAMP, EXPIRATION_TIME TIMESTAMP, IS_SIGN_UP BOOLEAN);

# --- !Downs

DROP TABLE TOKEN;
DROP TABLE "USER";
